/**
 * Seed data ported from the design prototype.
 *
 * This backs the mock API adapter so the UI runs before the Django backend
 * exists. Everything here is demo content flagged for replacement in the
 * handoff: five staff, eight services, three leave rows, the 192.168.1.42
 * printer and the alpinewerks.book.app URLs.
 */
import type {
  DocketSettings,
  Integration,
  LeaveEntry,
  NotificationEvent,
  PrinterSettings,
  Service,
  StaffMember,
  StoreSettings,
  TimeBlock,
} from "./types"
import type { BookingInterval, Day, ServiceCategory } from "./types"

export const DEMO_STORE_NAME = "Chamonix"

export const demoStaff: StaffMember[] = [
  {
    id: "s1",
    name: "Mara Lindqvist",
    role: "Rental Technician",
    initials: "ML",
    email: "mara@alpinewerks.co",
    phone: "+41 79 000 00 01",
    status: "Active",
    color: "#0284c7",
    availableHours: 40,
    daysOff: ["Wed"],
    bookingNotify: "every",
    canCheckEquipment: true,
    canCompleteAppointments: true,
  },
  {
    id: "s2",
    name: "Tobias Frei",
    role: "Ski Technician",
    initials: "TF",
    email: "tobias@alpinewerks.co",
    phone: "+41 79 000 00 02",
    status: "Active",
    color: "#0d9488",
    availableHours: 44,
    daysOff: ["Sun"],
    bookingNotify: "daily",
    canCheckEquipment: true,
    canCompleteAppointments: true,
  },
  {
    id: "s3",
    name: "Elena Rossi",
    role: "Lead Instructor",
    initials: "ER",
    email: "elena@alpinewerks.co",
    phone: "+41 79 000 00 03",
    status: "Active",
    color: "#d97706",
    availableHours: 42,
    daysOff: ["Mon"],
    bookingNotify: "every",
    canCheckEquipment: true,
    canCompleteAppointments: true,
  },
  {
    id: "s4",
    name: "Jonas Berg",
    role: "Boot Fitter",
    initials: "JB",
    email: "jonas@alpinewerks.co",
    phone: "+41 79 000 00 04",
    status: "Active",
    color: "#7c3aed",
    availableHours: 38,
    daysOff: ["Wed", "Sun"],
    bookingNotify: "none",
    canCheckEquipment: true,
    canCompleteAppointments: true,
  },
  {
    id: "s5",
    name: "Priya Nair",
    role: "Front Desk",
    initials: "PN",
    email: "priya@alpinewerks.co",
    phone: "+41 79 000 00 05",
    status: "Active",
    color: "#78716c",
    availableHours: 40,
    daysOff: [],
    bookingNotify: "every",
    canCheckEquipment: false,
    canCompleteAppointments: false,
  },
]

export const demoServices: Service[] = [
  { id: "sv1", name: "Ski Rental", category: "rental", duration: 20, price: "$45/day", enabled: true },
  { id: "sv2", name: "Snowboard Rental", category: "rental", duration: 20, price: "$45/day", enabled: true },
  { id: "sv3", name: "Ski Tune & Wax", category: "tuning", duration: 45, price: "$60", enabled: true },
  { id: "sv4", name: "Edge Sharpen", category: "tuning", duration: 30, price: "$35", enabled: true },
  { id: "sv5", name: "Binding Adjustment", category: "tuning", duration: 20, price: "$25", enabled: true },
  { id: "sv6", name: "Private Lesson", category: "lessons", duration: 120, price: "$180", enabled: true },
  { id: "sv7", name: "Group Lesson", category: "lessons", duration: 120, price: "$75", enabled: false },
  { id: "sv8", name: "Boot Fitting", category: "fitting", duration: 60, price: "$90", enabled: true },
]

let blockSeq = 0

function block(
  staffId: string,
  day: Day,
  start: string,
  end: string,
  services: ServiceCategory[],
  overrides: Partial<TimeBlock> = {}
): TimeBlock {
  blockSeq += 1
  return {
    id: `b${blockSeq}`,
    staffId,
    day,
    start,
    end,
    services,
    // Every bookable service in the block's categories starts selected.
    appointments: demoServices
      .filter((s) => s.enabled && services.includes(s.category))
      .map((s) => s.id),
    recurring: true,
    enabled: true,
    online: true,
    interval: 30 as BookingInterval,
    breaks: [],
    lead: {},
    ...overrides,
  }
}

export const demoTimeBlocks: TimeBlock[] = [
  // Mara Lindqvist — rentals and fitting
  block("s1", "Mon", "09:00", "12:00", ["rental", "fitting"]),
  block("s1", "Mon", "13:00", "17:00", ["rental", "tuning"]),
  block("s1", "Tue", "09:00", "17:00", ["rental"], { breaks: [{ start: "12:00", end: "12:30" }] }),
  block("s1", "Thu", "10:00", "14:00", ["rental", "lessons"], { online: false }),
  block("s1", "Fri", "09:00", "17:00", ["rental", "tuning", "fitting"]),
  block("s1", "Sat", "08:00", "18:00", ["rental", "lessons", "fitting"]),
  block("s1", "Sun", "08:00", "16:00", ["rental", "lessons"]),
  // Tobias Frei — tuning bench
  block("s2", "Mon", "08:00", "16:00", ["tuning"]),
  block("s2", "Tue", "08:00", "16:00", ["tuning"]),
  block("s2", "Wed", "08:00", "16:00", ["tuning"]),
  block("s2", "Thu", "08:00", "16:00", ["tuning"], { enabled: false }),
  block("s2", "Fri", "08:00", "16:00", ["tuning"]),
  block("s2", "Sat", "09:00", "15:00", ["tuning"]),
  // Elena Rossi — lessons
  block("s3", "Tue", "09:00", "12:00", ["lessons"]),
  block("s3", "Tue", "13:00", "16:00", ["lessons"]),
  block("s3", "Wed", "09:00", "16:00", ["lessons"]),
  block("s3", "Thu", "09:00", "16:00", ["lessons"]),
  block("s3", "Fri", "09:00", "16:00", ["lessons"]),
  block("s3", "Sat", "08:00", "17:00", ["lessons"], { interval: 120 }),
  block("s3", "Sun", "08:00", "17:00", ["lessons"], { interval: 120 }),
  // Jonas Berg — boot fitting
  block("s4", "Mon", "10:00", "18:00", ["fitting"], { interval: 60 }),
  block("s4", "Tue", "10:00", "18:00", ["fitting"], { interval: 60 }),
  block("s4", "Thu", "10:00", "18:00", ["fitting"], { interval: 60 }),
  block("s4", "Fri", "10:00", "18:00", ["fitting"], { interval: 60 }),
  block("s4", "Sat", "09:00", "17:00", ["fitting", "rental"], { interval: 60 }),
  // Priya Nair — front desk
  block("s5", "Mon", "08:00", "17:00", ["rental"]),
  block("s5", "Tue", "08:00", "17:00", ["rental"]),
  block("s5", "Wed", "08:00", "17:00", ["rental"]),
  block("s5", "Thu", "08:00", "17:00", ["rental"]),
  block("s5", "Fri", "08:00", "17:00", ["rental"]),
  block("s5", "Sat", "08:00", "18:00", ["rental"]),
  block("s5", "Sun", "08:00", "18:00", ["rental"]),
]

export const demoLeave: LeaveEntry[] = [
  { id: "l1", staffId: "s2", type: "Vacation", startDate: "2025-12-22", endDate: "2025-12-29", dates: "Dec 22 – Dec 29", days: 6 },
  { id: "l2", staffId: "s3", type: "Sick", startDate: "2025-12-11", endDate: "2025-12-11", dates: "Dec 11", days: 1 },
  { id: "l3", staffId: "s4", type: "Personal", startDate: "2026-01-05", endDate: "2026-01-06", dates: "Jan 5 – Jan 6", days: 2 },
]

export const demoStoreSettings: StoreSettings = {
  storeName: DEMO_STORE_NAME,
  booking: {
    onlineEnabled: true,
    url: "alpinewerks.book.app/alpine-werks",
    minNotice: { value: 2, unit: "h" },
    maxAhead: { value: 60, unit: "d" },
  },
  walkIn: {
    enabled: true,
    maxQueue: 15,
    cutoffWhenFull: true,
    notifyWhenClose: true,
    url: "alpinewerks.book.app/alpine-werks/check-in",
    serviceIds: ["sv1", "sv2", "sv4", "sv8"],
  },
  noPaymentSoftware: false,
}

export const demoIntegrations: Integration[] = [
  {
    id: "lightspeed",
    name: "Lightspeed",
    category: "Point of sale",
    description: "Sync products, customers, and sales from your POS.",
    connected: true,
    account: "Alpine Werks · Retail X",
    color: "#dc2626",
    initial: "L",
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "Online store",
    description: "Pull online orders and inventory into the workshop.",
    connected: false,
    account: "",
    color: "#0f766e",
    initial: "S",
  },
  {
    id: "square",
    name: "Square",
    category: "Payments",
    description: "Take payments on the counter and reconcile jobs.",
    connected: false,
    account: "",
    color: "#1c1917",
    initial: "S",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Charge deposits when customers book online.",
    connected: true,
    account: "acct · alpine-werks",
    color: "#6366f1",
    initial: "S",
  },
]

export const demoPrinter: PrinterSettings = {
  connection: "network",
  roll: "57mm thermal roll",
  autoPrint: true,
  ip: "192.168.1.42",
  port: "9100",
  model: "Epson TM-T88VII",
  protocol: "ESC/POS",
}

export const demoDocket: DocketSettings = {
  customerCopy: true,
  header: "PisteLabs",
  footer:
    "We are open daily from 7am-7pm.\nCheck us out online at www.pistelabs.com",
  customerEls: {
    logo: true,
    jobNumber: true,
    checkedIn: true,
    equipment: true,
    specs: true,
    services: true,
    prices: true,
    total: true,
    payNotice: true,
    barcode: true,
    footer: true,
  },
  shopEls: {
    jobNumber: true,
    itemCount: true,
    timestamp: true,
    equipment: true,
    specs: true,
    services: true,
    serviceDetail: true,
    notes: true,
    customer: true,
    barcode: true,
  },
}

/**
 * Notification templates — retained per the handoff even though the nav item
 * was removed for this release. Kept out of the UI until the screen returns.
 */
export const demoNotificationEvents: NotificationEvent[] = [
  {
    id: "n1",
    name: "Appointment confirmation",
    audience: "Customer",
    description: "Sent when an appointment is booked",
    sms: true,
    email: true,
    enabled: true,
    subject: "Your booking at Alpine Werks is confirmed",
    header: "Booking confirmed",
    body: "Hi {Name},\n\nYour appointment for {Equipmentservice} is confirmed. We have your {Equipment} on the list and will see you then.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, your Alpine Werks booking for {Equipmentservice} is confirmed.",
  },
  {
    id: "n2",
    name: "Appointment reminder",
    audience: "Customer",
    description: "Sent 24 hours before the appointment",
    sms: true,
    email: false,
    enabled: true,
    timingValue: 24,
    timingUnit: "h",
    timingWhen: "before",
    timingAnchor: "the appointment",
    subject: "Reminder: your appointment tomorrow",
    header: "See you tomorrow",
    body: "Hi {Name},\n\nA quick reminder about your {Equipmentservice} appointment. Please bring your {Equipment} with you.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, reminder: your {Equipmentservice} appointment is tomorrow.",
  },
  {
    id: "n3",
    name: "Appointment cancellation",
    audience: "Customer",
    description: "Sent when an appointment is cancelled",
    sms: true,
    email: true,
    enabled: true,
    subject: "Your appointment has been cancelled",
    header: "Appointment cancelled",
    body: "Hi {Name},\n\nYour {Equipmentservice} appointment has been cancelled. Get in touch any time to rebook.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, your Alpine Werks appointment has been cancelled.",
  },
  {
    id: "n4",
    name: "Service booking",
    audience: "Customer",
    description: "Sent when a service job is booked in",
    sms: false,
    email: true,
    enabled: true,
    subject: "Your service is booked in",
    header: "Service booked",
    body: "Hi {Name},\n\nWe have booked in {Equipmentservice}. Drop your {Equipment} at the counter and we will take it from there.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, your {Equipmentservice} is booked in at Alpine Werks.",
  },
  {
    id: "n5",
    name: "Service check-in",
    audience: "Customer",
    description: "Sent when equipment is checked in",
    sms: true,
    email: false,
    enabled: true,
    subject: "We have your equipment",
    header: "Checked in",
    body: "Hi {Name},\n\nYour {Equipment} is checked in for {Equipmentservice}. We will let you know as soon as it is ready.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, your {Equipment} is checked in at Alpine Werks.",
  },
  {
    id: "n6",
    name: "Service completion",
    audience: "Customer",
    description: "Sent when the job is ready for collection",
    sms: true,
    email: true,
    enabled: true,
    subject: "Your equipment is ready for collection",
    header: "Ready for collection",
    body: "Hi {Name},\n\n{Equipmentservice} is complete. Your {Equipment} is ready to collect during opening hours.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, your {Equipment} is ready to collect at Alpine Werks.",
  },
  {
    id: "n9",
    name: "Walk-in ready",
    audience: "Customer",
    description: "Sent when the customer is next in the queue",
    sms: true,
    email: false,
    enabled: true,
    subject: "You are next in the queue",
    header: "You are up next",
    body: "Hi {Name},\n\nYou are next in the queue at Alpine Werks. Please come to the counter with your {Equipment} and we will start {Equipmentservice}.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, you are next in the queue at Alpine Werks. Please come to the counter.",
  },
  {
    id: "n7",
    name: "Staff job assignment",
    audience: "Staff",
    description: "Sent to staff when a job is assigned to them",
    sms: false,
    email: true,
    enabled: false,
    subject: "A job has been assigned to you",
    header: "New job assigned",
    body: "Hi {Name},\n\n{Equipmentservice} has been added to your queue. The {Equipment} is on the rack.",
    footer: "Alpine Werks internal",
    smsBody: "Hi {Name}, {Equipmentservice} has been assigned to you.",
  },
  {
    id: "n8",
    name: "Review reminder",
    audience: "Customer",
    description: "Sent 48 hours after completion",
    sms: false,
    email: true,
    enabled: true,
    timingValue: 48,
    timingUnit: "h",
    timingWhen: "after",
    timingAnchor: "completion",
    subject: "How did we do?",
    header: "Thanks for visiting",
    body: "Hi {Name},\n\nWe hope your {Equipment} is running well after {Equipmentservice}. A short review would mean a lot.",
    footer: "Alpine Werks · Dorfstrasse 12 · +41 79 000 00 00",
    smsBody: "Hi {Name}, how did we do? Leave Alpine Werks a quick review.",
  },
]
